simple_bus_aws_bridge:
  credentials:
    key: "%env(AWS_KEY)%"
    secret: "%env(AWS_SECRET)%"
    region: "%env(AWS_REGION)%"
  topic:
    name: "%env(AWS_TOPIC_ARN)%"
    version: "%env(AWS_SDK_VERSION)%"
    asynchronous_events:
      - 'App\Comment\Domain\ValueObject\CommentUpsertedEvent'

simple_bus_asynchronous:
  events:
    strategy: 'predefined'
    publisher_service_id: BNNVARA\SimpleBusAwsBridge\Publisher\SnsPublisher
